DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS vote;
DROP TABLE IF EXISTS eaten;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  teamid INTEGER NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE vote (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  teamid INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  eatdate DATE NOT NULL,
  meal TEXT NOT NULL,
  canteen TEXT NOT NULL,
  FOREIGN KEY (author_id, teamid) REFERENCES user (id, teamid)
);

CREATE TABLE eaten (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  teamid INTEGER NOT NULL,
  eatdate DATE NOT NULL,
  meal TEXT NOT NULL,
  canteen TEXT NOT NULL,
  votes INTEGER NOT NULL,
  FOREIGN KEY (teamid) REFERENCES user (teamid)
);